name: 'Branch'

run-name: Test ${{ github.ref_name }}

on:
  push:
    branches:
      - master

concurrency:
  group: test-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/workflow_test.yml
