name: "Cargo update"
on:
  schedule:
    - cron: "0 5 * * 1" # Runs at 05:00, only on Monday

jobs:
  cargo-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Run Update
        run: cargo update --verbose

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: Cargo update
          branch: github-actions/build/deps/cargo-update
          commit-message: "build(deps): cargo update"
          body: Automated cargo update
          labels: dependencies rust
